puts 'SubgruposPrestacion'
subgrupo_prestacion_list = [
	[1,3,'I.- SANGRE, HEMATOLOGIA',''],
	[2,3,'II.- SANGRE, EXAMENES BIOQUIMICOS',''],
	[3,3,'III.- HORMONAS A.- EN SANGRE',''],
	[4,3,'III.- HORMONAS B.- EN ORINA',''],
	[5,3,'IV.- GENETICA',''],
	[6,3,'V.- INMUNOLOGIA A.- INMUNOQUIMICA',''],
	[7,3,'V.- INMUNOLOGIA B.- INMUNOCELULARES',''],
	[8,3,'V.- INMUNOLOGIA C.- HISTOCOMPATIBILIDAD',''],
	[9,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.1 EXAMENES MICROSCOPICOS',''],
	[10,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.2 CULTIVOS','Incluye la identificación bioquímica y serológica cuando corresponda'],
	[11,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.3 CULTIVOS ESPECIFICOS PARA',''],
	[12,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.4 ANTIBIOGRAMA',''],
	[13,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.5 OTROS',''],
	[14,3,'VI.- EXAMENES MICROBIOLOGICOS A.- BACTERIAS Y HONGOS A.6 SEROLOGICOS','Determinación de antígenos o anticuerpos'],
	[15,3,'VI.- EXAMENES MICROBIOLOGICOS B. PARASITOS B.1 MACRO Y MICROSCOPICOS',''],
	[16,3,'VI.- EXAMENES MICROBIOLOGICOS B. PARASITOS B.2. SEROLOGICOS','Determinación de antígenos y anticuerpos'],
	[17,3,'VI.- EXAMENES MICROBIOLOGICOS C. VIRUS C.1 CULTIVOS',''],
	[18,3,'VI.- EXAMENES MICROBIOLOGICOS C. VIRUS C.2 SEROLOGIA','Determinación de antígenos o anticuerpos'],
	[19,3,'VII.- PROCEDIMIENTOS O DETERMINACIONES DIRECTAMENTE CON EL PACIENTE','NO INCLUYE LOS FARMACOS NI LOS EXAMENES BIOQUIMICOS QUE CORRESPONDAN'],
	[20,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS A. DEPOSICIONES',''],
	[21,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.1 EXAMENES GENERALES',''],
	[22,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.1. L.C.R.',''],
	[23,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.2. LIQUIDO ARTICULAR',''],
	[24,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.3. LIQUIDOS GASTROINTESTINALES A) JUGO GASTRICO',''],
	[25,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.3. LIQUIDOS GASTROINTESTINALES B) JUGO PANCREATICO',''],
	[26,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.3. LIQUIDOS GASTROINTESTINALES C) JUGO DUODENAL',''],
	[27,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.4. LIQUIDO SEMINAL',''],
	[28,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.5. LIQUIDO AMNIOTICO',''],
	[29,3,'VIII.- EXAMENES DE DEPOSICIONES, EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B. EXUDADOS, SECRECIONES Y OTROS LIQUIDOS B.2 EXAMENES ESPECIALES B.2.6. CERVICO UTERINO VAGINAL',''],
	[30,3,'IX.- EXAMENES ORINA',''],
	[31,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES',''],
	[32,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES CUELLO',''],
	[33,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES TORAX',''],
	[34,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES GLANDULAS MAMARIAS',''],
	[35,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES ABDOMEN',''],
	[36,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES APARATO DIGESTIVO',''],
	[37,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES APARATO UROGENITAL',''],
	[38,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES CRANEO',''],
	[39,4,' I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES COLUMNA VERTEBRAL',''],
	[40,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES EXTREMIDADES',''],
	[41,4,'I.- EXAMENES RADIOLOGICOS. A.- EXAMENES RADIOLOGICOS SIMPLES PROCEDIMIENTO FLUOROSCOPICO DE APOYO:',''],
	[42,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS OJOS','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[43,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS GLANDULAS MAMARIAS','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[44,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS ABDOMEN','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[45,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS APARATO UROGENITAL','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[46,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS COLUMNA','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[47,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS ARTICULARES','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[48,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS CARDIOVASCULARES','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[49,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS FLEBOGRAFIAS','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[50,4,'I.- EXAMENES RADIOLOGICOS.  B.- EXAMENES RADIOLOGICOS COMPLEJOS MIELOGRAFIAS','En los casos que corresponde, el Arancel incluye el valor del procedimiento médico necesario para efectuar el examen.'],
	[51,4,'II.- TOMOGRAFIA AXIAL COMPUTARIZADA (TAC) (CON O SIN MEDIO DE CONTRASTE)',''],
	[52,4,'III.- ULTRASONOGRAFIA A.- EQUIPOS SIMPLES','Mínimo 6 imágenes diferentes para ecotomografías'],
	[53,4,'III.- ULTRASONOGRAFIA B.- EQUIPOS DE MEDIANA A ALTA RESOLUCION','Mínimo 6 imágenes diferentes para ecotomografías'],
	[54,4,'III.- ULTRASONOGRAFIA C.- EQUIPOS DE ALTA RESOLUCION.','Mínimo 6 imágenes diferentes para ecotomografías'],
	[55,4,'III.- ULTRASONOGRAFIA D.- EQUIPOS CON DOPPLER.','Mínimo 6 imágenes diferentes para ecotomografías'],
	[56,4,'IV.- RESONANCIA MAGNÉTICA','Incluye medio de contraste'],
	[57,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 1.- ESTUDIOS ENDOCRINOLÓGICOS','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[58,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 2.- ESTUDIOS OSTEOARTICULARES','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[59,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 3.- ESTUDIOS CARDIOVASCULARES','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[60,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 4.- ESTUDIOS DIGESTIVOS','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[61,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 5.- ESTUDIOS NEFROUROLÓGICOS','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[62,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 6.- ESTUDIOS PULMONARES','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[63,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 7.- ESTUDIOS SISTEMA NERVIOSO CENTRAL','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[64,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 8.- ESTUDIOS DE INFECCIONES','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[65,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 9.- ESTUDIOS ONCOLÓGICOS','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[66,5,'I.- MEDICINA NUCLEAR A.- PROCEDIMIENTOS DIAGNOSTICOS 10.- DENSITOMETRÍA OSEA','Incluye valor del radiofármaco o radioisótopos y procedimiento correspondiente, salvo que se especifíque'],
	[67,5,'I.- MEDICINA NUCLEAR B.- PROCEDIMIENTOS TERAPEUTICOS. RADIOISOTOPOS','no incluye procedimiento médico'],
	[68,5,'II.- RADIOTERAPIA BRAQUITERAPIA','La unidad rad se considera como tal o su equivalente biológico (Gray * o similar) según sea la técnica empleada. Para todos los casos, los valores corresponden a la planificación, simulación y tratamiento integral, el cual incluye la substancia radioactiva, la irradiación en una o más zonas anatómicas, en sesiones continuas, diarias o semanales según corresponda. Incluyen, además, el control clínico y el tratamiento de las complicaciones derivadas de las irradiaciones, hasta 20 días después de finalizadas éstas.'],
	[69,5,'II.- RADIOTERAPIA RADIOTERAPIA CON ACELERADOR LINEAL DE ELECTRONES','La unidad rad se considera como tal o su equivalente biológico (Gray * o similar) según sea la técnica empleada. Para todos los casos, los valores corresponden a la planificación, simulación y tratamiento integral, el cual incluye la substancia radioactiva, la irradiación en una o más zonas anatómicas, en sesiones continuas, diarias o semanales según corresponda. Incluyen, además, el control clínico y el tratamiento de las complicaciones derivadas de las irradiaciones, hasta 20 días después de finalizadas éstas.'],
	[70,5,'II.- RADIOTERAPIA TELECOBALTOTERAPIA','La unidad rad se considera como tal o su equivalente biológico (Gray * o similar) según sea la técnica empleada. Para todos los casos, los valores corresponden a la planificación, simulación y tratamiento integral, el cual incluye la substancia radioactiva, la irradiación en una o más zonas anatómicas, en sesiones continuas, diarias o semanales según corresponda. Incluyen, además, el control clínico y el tratamiento de las complicaciones derivadas de las irradiaciones, hasta 20 días después de finalizadas éstas.'],
	[71,5,'II.- RADIOTERAPIA ROENTGENTERAPIA.','La unidad rad se considera como tal o su equivalente biológico (Gray * o similar) según sea la técnica empleada. Para todos los casos, los valores corresponden a la planificación, simulación y tratamiento integral, el cual incluye la substancia radioactiva, la irradiación en una o más zonas anatómicas, en sesiones continuas, diarias o semanales según corresponda. Incluyen, además, el control clínico y el tratamiento de las complicaciones derivadas de las irradiaciones, hasta 20 días después de finalizadas éstas.'],
	[72,7,'Preparación de Hemocomponentes',''],
	[73,7,'Estudios Previos a Transfusión por tipo de Hemocomponente',''],
	[74,7,'Procedimientos transfusionales',''],
	[75,8,'ANATOMIA PATOLOGICA',''],
	[76,9,'PSIQUIATRIA Y SALUD MENTAL',''],
	[77,11,'I.- PROCEDIMIENTOS DIAGNOSTICOS',''],
	[78,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA A.- CUERO CABELLUDO LESIONES VASCULARES:','(Heridas tumores y quistes benignos,  absceso, flegmón del cuero cabelludo, véase tegumentos)'],
	[79,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA B.- CRANEO',''],
	[80,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA B.- CRANEO DEFECTO ÓSEO:',''],
	[81,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA B.- CRANEO CRANEOESTENOSIS:',''],
	[82,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA B.- CRANEO  CIRUGÍA REPARADORA CRÁNEO-ÓRBITO-FACIAL:','-  AVANCE FRONTO-ORBITARIO BILATERAL EN CRANEOESTENOSIS COMPLEJAS - REPARACION DE HIPERTELORISMO -  REPARACION DE MENINGOENCEFALOCELE FRONTOETMOIDAL - CIRUGIA REPARADORA EN DISPLASIA FIBROSA FRONTOETMOIDAL O ESFENOIDAL (Participan tres o más equipos de especialistas; como 1er. cirujano: neurocirujano, de cabeza y cuello, de plástica, máxilo-facial, oftalmólogo, otorrinolaringólogo u otros).'],
	[83,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[84,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS TUMORES Y/O QUISTES Y/O CAVERNOMA (EXTIRPACION DE)','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[85,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS LESIONES VASCULARES, TRATAMIENTO QUIRURGICO:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[86,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS FISTULA CAROTIDO CAVERNOSA:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[87,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS ANASTOMOSIS Y REVASCULARIZACION CEREBRAL:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[88,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS CIRUGÍA DERIVATIVA DE LCR:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[89,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS MALFORMACIONES:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[90,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS NERVIOS CRANEANOS:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[91,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS CIRUGÍA DE LA EPILEPSIA:','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[92,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA C.- ENCEFALO Y ENVOLTURAS ESTEREOTAXIA Y CIRUGÍA FUNCIONAL','Para cirugía endovascular no individualizada, se aplicarán los códigos y valores de las técnicas convencionales, aumentando en dos dígitos el código adicional.'],
	[93,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA D.-  COLUMNA Y MEDULA ','Además, ver grupo 21 Columna'],
	[94,11,'II.- INTERVENCIONES QUIRURGICAS. NEUROCIRUGIA E.- NERVIOS PERIFERICOS Y PLEXOS',''],
	[95,12,'A.- VIA LAGRIMAL',''],
	[96,12,'B.- SACO Y/O GLANDULA LAGRIMAL',''],
	[97,12,'C.- PARPADO Y CEJA (SUPERIOR O INFERIOR)',''],
	[98,12,'D.- CONJUNTIVA',''],
	[99,12,'E.- ORBITA',''],
	[100,12,'F.- GLOBO Y MUSCULOS OCULARES',''],
	[101,12,'G.- CORNEA Y ESCLEROTICA',''],
	[102,12,'H.- IRIS Y CUERPO CILIAR',''],
	[103,12,'I.- COROIDES, CAMARA POSTERIOR Y RETINA',''],
	[104,12,'J.- CRISTALINO Y CUERPO CILIAR',''],
	[105,12,'INTERVENCIONES CON LASER',''],
	[106,13,'OIDO EXTERNO',''],
	[107,13,'OIDO MEDIO',''],
	[108,13,'OIDO MEDIO Y EXTERNO',''],
	[109,13,'OIDO INTERNO Y NERVIO ACUSTICO',''],
	[110,13,'NERVIO FACIAL',''],
	[111,13,'BOCA Y FARINGE',''],
	[112,13,'ABSCESO O FLEGMON DE, TRAT. QUIR.:',''],
	[113,13,'Tumor de la base de la lengua, extirpación de:',''],
	[114,13,'NARIZ, SENOS PARANASALES Y VIAS LAGRIMALES',''],
	[115,13,'LARINGE Y TRAQUEA',''],
	[116,13,'Cuerdas vocales, tumores benignos, trat. quir.',''],
	[117,14,'TIROIDES',''],
	[118,14,'Tiroidectomía:',''],
	[119,14,'PARATIROIDES (UN LADO) Adenoma y/o hiperplasia, trat. quir.',''],
	[120,14,'GLANDULAS SALIVALES PAROTIDA (UN LADO) Parotidectomía',''],
	[121,14,'GLANDULAS SALIVALES GLANDULA SUB-MANDIBULAR',''],
	[122,14,'GLANDULAS SALIVALES SUB-LINGUAL (UNA O AMBAS)',''],
	[123,14,'GLANDULAS SALIVALES Otros',''],
	[124,14,'OTRAS ESTRUCTURAS PROFUNDAS DE CUELLO',''],
	[125,14,'PIEL Y MUCOSAS',''],
	[126,14,'TUMORES MALIGNOS:',''],
	[127,14,'NARIZ',''],
	[128,14,'CAVIDADES PARANASALES Y HUESO TEMPORAL',''],
	[129,14,'MAXILECTOMIA',''],
	[130,14,'CAVIDAD ORAL Y OROFARINGEA',''],
	[131,14,'RESECCION DE MANDIBULA',''],
	[132,14,'HIPOFARINGE Y ESOFAGO CERVICAL',''],
	[133,14,'CIRUGIA OSTEOTOMICA  SOBRE LOS MAXILARES',''],
	[134,14,'TRAUMATOLOGIA MAXILO FACIAL','Fracturas del malar, maxilar superior, mandíbula y orbitarias, únicas o múltiples, excluida nariz.'],
	[135,15,'Heridas de la cara (cortantes y/o contusas), sutura plástica (proc. aut.)',''],
	[136,15,'Cicatrices (cualquier localización o tamaño), resecc. plástica de (proc. aut.)',''],
	[137,15,'Injertos piel parcial y/o mucosa (incluye tratamiento zonas dadora y receptora)',''],
	[138,15,'Toma de injertos',''],
	[139,15,'Colgajos - Plastías en Z','si se utilizan colgajos para corregir o resecar lesiones benignas o malignas sólo se cobrará el colgajo)'],
	[140,15,'Colgajos (rotación, avance, deslizamiento, al azar o similar)','si se utilizan colgajos para corregir o resecar lesiones benignas o malignas sólo se cobrará el colgajo)'],
	[141,15,'CRANEO Y CARA',''],
	[142,15,'CRANEO Y CARA - Ridectomía',''],
	[143,15,'OREJAS (UN LADO)',''],
	[144,15,'NARIZ',''],
	[145,15,'PARPADOS',''],
	[146,15,'LABIOS',''],
	[147,15,'AFECCIONES CONGENITAS',''],
	[148,15,'RECONSTRUCCION OSTEOPLASTICA REBORDE ALVEOLAR',''],
	[149,15,'HIPERTELORISMO',''],
	[150,15,'CIRUGIA DE LA MAMA (Un lado)','Véase Ginecología y Obstetricia, cód. 20-02-001 al 20-02-005'],
	[151,15,'ABDOMEN Y PELVIS',''],
	[152,15,'TRATAMIENTO DE ESCARAS DE DECUBITO',''],
	[153,15,'EXTREMIDADES',''],
	[154,15,'PROCEDIMIENTOS EN ESCARAS','(Quemaduras, loxoscelismo o similar)'],
	[155,15,'Escarectomía',''],
	[156,16,'Biopsia de piel y/o mucosa por curetaje o sección tangencial c/s electro x 1 lesión',''],
	[157,16,'Extirpación, reparación o biopsia, total o parcial, de lesiones benignas cutáneas por excisión',''],
	[158,16,'Tumor maligno por excisión total o parcial, con o sin sutura, por cada lesión',''],
	[159,16,'Ampliación de márgenes quirúrgicos de tumor maligno extirpado previamente',''],
	[160,16,'Extirpación de lesión benigna subepidérmica, incluye Tumor sólido, quiste epidérmico y lipoma por lesión',''],
	[161,17,'PROC. DIAGNOSTICO Y TERAPEUTICO',''],
	[162,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 1.- OPERACIONES SOBRE EL SISTEMA ARTERIAL','Para cirugía videoendoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales'],
	[163,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 2.- OPERACIONES SOBRE EL SISTEMA VENOSO',''],
	[164,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 3.- OPERACIONES SOBRE EL SISTEMA LINFATICO LINFATICOS',''],
	[165,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 3.- OPERACIONES SOBRE EL SISTEMA LINFATICO GANGLIOS',''],
	[166,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 3.- OPERACIONES SOBRE EL SISTEMA LINFATICO DISECCION Y EXTIRPACION  GANGLIONAR REGIONAL (proc. aut.):',''],
	[167,17,'CIRUGIA CARDIOVASCULAR A. CIRUGIA VASCULAR PERIFERICA 4.- SIMPATECTOMIA:',''],
	[168,17,'CIRUGIA CARDIOVASCULAR B. CIRUGIA CARDIACA PERICARDIO Y CORAZON',''],
	[169,17,'CIRUGIA CARDIOVASCULAR B. CIRUGIA CARDIACA OPERACIONES CARDIACAS','Incluyen la toma de puentes venosos'],
	[170,17,'CIRUGIA DE TORAX PARED TORACICA.',''],
	[171,17,'CIRUGIA DE TORAX MEDIASTINO',''],
	[172,17,'CIRUGIA DE TORAX DIAFRAGMA',''],
	[173,17,'CIRUGIA DE TORAX PLEURA',''],
	[174,17,'CIRUGIA DE TORAX TRAQUEA Y BRONQUIO','Ver, además, Otorrinolaringología'],
	[175,17,'CIRUGIA DE TORAX PULMON (CADA LADO)',''],
	[176,17,'CIRUGIA DE TORAX ESOFAGO',''],
	[177,18,'PROC. DIAGNOSTICO Y TERAPEUTICO INCLUYE USO DE ANESTESIA TOPICA',''],
	[178,18,'CIRUGIA ABDOMINAL - HERNIAS, TRATAMIENTO QUIRURGICO','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el código respectivo'],
	[179,18,'CIRUGIA ABDOMINAL - PARED ABDOMINAL',''],
	[180,18,'CIRUGIA ABDOMINAL - PERITONEO',''],
	[181,18,'CIRUGIA ABDOMINAL - ESTOMAGO',''],
	[182,18,'CIRUGIA ABDOMINAL - HIGADO Y VIAS BILIARES',''],
	[183,18,'CIRUGIA ABDOMINAL - PANCREAS',''],
	[184,18,'CIRUGIA ABDOMINAL -  BAZO',''],
	[185,18,'CIRUGIA ABDOMINAL -  INTESTINOS DELGADO Y GRUESO',''],
	[186,18,'CIRUGIA PROCTOLOGICA - RECTO Y ANO',''],
	[187,19,'DIALISIS','Incluyen aplicación de la técnica, control clínico permanente y el tratamiento de las complicaciones médicas'],
	[188,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - RIÑON','Todas las intervenciones quirúrgicas se refieren a un lado cuando corresponda.'],
	[189,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - SUPRARRENAL',''],
	[190,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - URETER',''],
	[191,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - VEJIGA',''],
	[192,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - URETRA',''],
	[193,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - PROSTATA Y VESICULAS SEMINALES',''],
	[194,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - TESTICULOS Y SUS ANEXOS ',''],
	[195,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - EPIDIDIMO Y CONDUCTO DEFERENTE',''],
	[196,19,'CIRUGIA UROLOGICA Y SUPRARRENAL - PENE',''],
	[197,20,'PROCEDIMIENTOS DIAGNOSTICOS Y TERAPEUTICOS - ENDOSCOPIAS C/S BIOPSIAS C/S TOMA DE MUESTRAS',''],
	[198,20,'PROCEDIMIENTOS DIAGNOSTICOS Y TERAPEUTICOS - OTRAS EXPLORACIONES',''],
	[199,20,'PROCEDIMIENTOS DIAGNOSTICOS Y TERAPEUTICOS - PROCEDIMIENTOS PARA EXAMENES RADIOLOGICOS',''],
	[200,20,'PROCEDIMIENTOS DIAGNOSTICOS Y TERAPEUTICOS - OTROS PROCEDIMIENTOS',''],
	[201,20,'CIRUGIA DE LA MAMA (UN LADO)','Véase, además, Cirugía Plástica y Reparadora, cód. 15-02-047 al 15-02-052'],
	[202,20,'CIRUGIA GINECOLOGICA - Videolaparoscopía','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el cód. respectivo'],
	[203,20,'CIRUGIA GINECOLOGICA - OVARIO Y TROMPA DE FALOPIO','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el cód. respectivo'],
	[204,20,'CIRUGIA GINECOLOGICA - UTERO Y SUS ELEMENTOS DE SOSTEN','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el cód. respectivo'],
	[205,20,'CIRUGIA GINECOLOGICA - VAGINA','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el cód. respectivo'],
	[206,20,'CIRUGIA GINECOLOGICA - VULVA Y PERINE','Para cirugía videolaparoscópica no individualizada como tal, se aplicarán los códigos y valores de las técnicas convencionales. Cuando la prestación requiere laparotomía, ella esta incluida en el cód. respectivo'],
	[207,20,'CIRUGIA  OBSTETRICA Y PARTOS - ABORTO',''],
	[208,20,'CIRUGIA  OBSTETRICA Y PARTOS - OPERACION CESAREA',''],
	[209,20,'CIRUGIA  OBSTETRICA Y PARTOS - PARTOS','el arancel no incluye anestesia si fuera necesario'],
	[210,21,'TRAUMATOLOGIA','Tanto para procedimientos e intervenciones quirúrgicas generales como segmentarias del párrafo siguiente, si se usan técnicas de reducción y fijaciones externas, percutáneas, con tutores metálicos, o de cirugía video-artroscópica, se aplicarán los mismos códigos y valores de las técnicas convencionales. En el caso de una intervención que necesite la colocación de un aparato enyesado, o yeso, este se considera incluido en el valor de la prestación.'],
	[211,21,'ARTRODESIS',''],
	[212,21,'FRACTURAS EXPUESTAS','Comprende el aseo quirúrgico, el manejo de partes blandas, la técnica de osteosíntesis empleada y/o la colocación de aparatos enyesados'],
	[213,21,'INFECCIONES OSEAS',''],
	[214,21,'INFECCIONES ARTICULARES','Sinovitis, artritis, u osteoartr. sépticas; c/s artroclisis'],
	[215,21,'INJERTOS OSEOS','Incluye toma e implantación.  Procedimiento simultáneo o sucesivo con otra intervención quirúrgica; se agrega al valor de la operación principal'],
	[216,21,'TUMORES O QUISTES O LESIONES PSEUDOTUMORALES, OSEOS O MUSCULARES',''],
	[217,21,'SINOVECTOMIAS QUIRURGICAS  (proc. aut.)',''],
	[218,21,'NEUROLISIS - NEURORRAFIAS - NEURECTOMIAS','Véase Neurocirugía cód. 11-03-058 al 11-03-063 y 11-03-068'],
	[219,21,'BIOPSIA SINOVIAL, ÓSEA O MUSCULAR (proc. aut.)',''],
	[220,21,'OTROS',''],
	[221,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - HOMBRO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[222,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - HUMERO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[223,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - CODO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[224,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - ANTEBRAZO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[225,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - MUÑECA','Para síndrome de Túnel Carpiano, ver cód. 11-03-066. Todas las intervenciones quirúrgicas se refieren a un lado'],
	[226,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - MANO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[227,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - COLUMNA','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[228,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - PELVIS','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[229,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - CADERA','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[230,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - MUSLO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[231,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - RODILLA','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[232,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - PIERNA','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[233,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - TOBILLO','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[234,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - PIE','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[235,21,'INTERVENCIONES QUIRURGICAS SEGMENTARIAS - RETIRO DE ELEMENTOS DE OSTEOSINTESIS','Todas las intervenciones quirúrgicas se refieren a un lado'],
	[236,21,'PROCEDIMIENTOS ORTOPEDICOS 1. LUXACIONES','Comprende maniobras de reducción, c/s tracción esquelética (transesquelética o craneal) provisoria o definitiva y colocación de yeso.'],
	[237,21,'PROCEDIMIENTOS ORTOPEDICOS 2.- FRACTURAS CON O SIN LUXACION','Comprende fracturas desplazadas o anguladas, fracturas en tallo verde anguladas y fracturas o disyunciones desplazadas; incluye maniobras de reducción (c/s tracción transesquelética o craneal) provisoria o definitiva y colocación de yeso. En caso de fracturas de 2 huesos del mismo segmento anatómico, se facturará el 100% de la prestación de mayor valor más el 50% de la segunda.'],
	[238,21,'MALFORMACIONES CONGENITAS','Comprende el tratamiento ortopédico con los cambios de yesos o el ajuste y control del aparataje empleado'],
	[239,22,'ANESTESIA',''],
	[240,24,'RESCATES, TRASLADOS Y RONDAS RURALES',''],
	[241,25,'PAGO ASOCIADO A DIAGNOSTICO (PAD)',''],
	[242,27,'NIVEL PRIMARIO - ACTIVIDADES PREVENTIVAS',''],
	[243,27,'OTRAS ACTIVIDADES DE NIVEL PRIMARIO',''],
	[244,27,'NIVEL SECUNDARIO',''],
	[245,27,'NIVEL TERCIARIO',''],
	[246,30,'LENTES Y AUDIFONOS',''],
	[247,30,'TUMORES DEL ADULTO',''],
	[248,30,'TUMORES INFANTILES',''],
	[249,30,'Tumores Cerebrales Infantiles',''],
	[250,30,'TRATAMIENTO ABREVIADO DE LA TUBERCULOSIS','']
]

ActiveRecord::Base.transaction do
	subgrupo_prestacion_list.each do |id, grupo, nombre, descripcion|
	  MedPrestacionesSubgrupos.create! id: id, grupo: MedPrestacionesGrupos.find(grupo), nombre: nombre, descripcion: descripcion
	end
end