puts 'GruposPrestaciones'
G1 = MedPrestacionesGrupos.create! :id => 3 , :nombre => 'EXAMENES DE LABORATORIO', :descripcion => ''
G2 = MedPrestacionesGrupos.create! :id => 4 , :nombre => 'IMAGENOLOGIA', :descripcion => ''
G3 = MedPrestacionesGrupos.create! :id => 5 , :nombre => 'MEDICINA NUCLEAR Y RADIOTERAPIA', :descripcion => ''
G4 = MedPrestacionesGrupos.create! :id => 7 , :nombre => 'MEDICINA TRANSFUSIONAL', :descripcion => 'Transfusión de hemocomponentes. Cobro de acto transfusional por cada 4 unidades de glóbulos rojos o plasma, y por cada 6 unidades de crioprecipitados o plaquetas. Incluye el tratamiento de las complicaciones medicas inmediatas. No incluye preparación de hemocomponentes ni estudios previos, salvo que el procedimiento transfusional así lo explicite.'
G5 = MedPrestacionesGrupos.create! :id => 8 , :nombre => 'ANATOMIA PATOLOGICA', :descripcion => ''
G6 = MedPrestacionesGrupos.create! :id => 9 , :nombre => 'PSIQUIATRIA Y SALUD MENTAL', :descripcion => ''
G7 = MedPrestacionesGrupos.create! :id => 11 , :nombre => 'NEUROLOGIA Y NEUROCIRUGIA', :descripcion => ''
G8 = MedPrestacionesGrupos.create! :id => 12 , :nombre => 'CIRUGIA OFTALMOLOGICA', :descripcion => 'Además, véase Cirugía Plástica y Reparadora, y Cirugía de Cabeza y Cuello. Todas las intervenciones se refieren a un ojo y sus anexos, salvo que se especifique otra cosa.'
G9 = MedPrestacionesGrupos.create! :id => 13 , :nombre => 'CIRUGIA OTORRINOLARINGOLOGICA', :descripcion => 'En los casos de realización de técnicas endoscópicas y en ausencia de códigos para ellos, se aplicarán los correspondientes a las técnicas convencionales. Para el código adicional se aplicará en estos casos, el correspondiente a la intervención convencional aumentado en dos dígitos. Véase, además, Cirugía Plástica y Reparadora y Cirugía de Cabeza y Cuello. Todas las intervenciones sobre el oído se refieren a un lado.'
G10 = MedPrestacionesGrupos.create! :id => 14 , :nombre => 'CIRUGIA DE CABEZA Y CUELLO', :descripcion => 'Además, véase intervenciones quirúrgicas de Oftalmología, Otorrinolaringología y Cirugía Plástica y Reparadora.'
G11 = MedPrestacionesGrupos.create! :id => 15 , :nombre => 'CIRUGIA PLASTICA Y REPARADORA', :descripcion => ''
G12 = MedPrestacionesGrupos.create! :id => 16 , :nombre => 'DERMATOLOGIA Y TEGUMENTOS', :descripcion => 'CIRUGIAS. En sala de procedimientos o pabellón quirúrgico.'
G13 = MedPrestacionesGrupos.create! :id => 17 , :nombre => 'CARDIOLOGIA', :descripcion => ''
G14 = MedPrestacionesGrupos.create! :id => 18 , :nombre => 'GASTROENTEROLOGIA', :descripcion => ''
G15 = MedPrestacionesGrupos.create! :id => 19 , :nombre => 'UROLOGIA Y NEFROLOGIA', :descripcion => ''
G16 = MedPrestacionesGrupos.create! :id => 20 , :nombre => 'GINECOLOGIA Y OBSTETRICIA', :descripcion => ''
G17 = MedPrestacionesGrupos.create! :id => 21 , :nombre => 'TRAUMATOLOGIA', :descripcion => ''
G18 = MedPrestacionesGrupos.create! :id => 22 , :nombre => 'ANESTESIA', :descripcion => ''
G19 = MedPrestacionesGrupos.create! :id => 24 , :nombre => 'RESCATES, TRASLADOS Y RONDAS RURALES', :descripcion => ''
G20 = MedPrestacionesGrupos.create! :id => 25 , :nombre => 'PAGO ASOCIADO A DIAGNOSTICO (PAD)', :descripcion => ''
G21 = MedPrestacionesGrupos.create! :id => 27 , :nombre => 'ATENCION ODONTOLOGICA', :descripcion => 'Incluye el valor del derecho a pabellón cuando corresponde'
G22 = MedPrestacionesGrupos.create! :id => 30 , :nombre => 'GRUPO DE PRESTACIONES: lentes, audífonos, PNDA y TBC.', :descripcion => ''